**Deep Learning (first) Video Tutorial**,  Mehr 30, Posted in the Skype Class Room, DL Recitation

[Deep Learning](https://github.com/hhaji/Deep-Learning), Data Science Center, Shahid Beheshti University

Presented and written by [‌‌Yavar Taheri Yeganeh](https://github.com/YavarYeganeh)



### 1) Introduction to Python Classes and Objects
### 2) Building fully connected neural networks without using machine learning libraries in Python

**External Resources on Python Object-oriented programming:**

* https://en.wikipedia.org/wiki/Object-oriented_programming

* https://docs.python.org/3/tutorial/classes.html

* https://www.w3schools.com/python/python_classes.asp  

* https://www.geeksforgeeks.org/python-classes-and-objects/

<table align="left">
  <td>
    <a target="_blank" href=https://colab.research.google.com/drive/1MswS0QON4atGHxm85oXqCCKR2fypo7Su?usp=sharing"><img src="https://colab.research.google.com/img/colab_favicon_256px.png" height="100" width="100" /> <br>  Run in Google Colab</a>
  </td>
</table>

In [ ]:
# We may only need numpy
import numpy as np

In [ ]:
# Defining activations
def sigmoid(x):
  y=1/(1 + np.exp(-x))
  return y
def tanh(x):
  y=np.tanh(x)
  return y
def relu(x):
  if x<0:
    return 0
  else:
    return x
## Add more activations ##

In [ ]:
# A class for a layer
class layer:   
  def __init__(self, input_dim, out_dim, activation):
    self.input_dim=input_dim
    self.out_dim=out_dim   
    self.w=[[np.random.randn() for i in range(self.input_dim)] for j in range(self.out_dim)]
    self.b=[np.random.randn() for i in range(self.out_dim)]
    if activation=='sigmoid':
      self.activation=sigmoid
    elif activation=='tanh':
      self.activation=tanh
    elif activation=='relu':
      self.activation=relu
    else:
      print('The activation argument is not valid for this layer. Tanh is selected as default')
      self.activation=tanh    
  def forward(self, input):
    output=[]
    for i in range(self.out_dim):
      neuron_input=0
      for j in range(self.input_dim):
        neuron_input += input[j]*self.w[i][j]
      neuron_input += self.b[i]
      output.append(self.activation(neuron_input))
    return np.array(output)

In [ ]:
# A class for Neural Network
class NN:
  def __init__(self, layers_dimensions, activations):
    self.layers_dimensions=layers_dimensions
    self.activations=activations
    self.layers=[]
    for i in range (len(layers_dimensions)-1): # I assumed to have layers_dimensions[0] as input dimension 
      self.layers.append(layer(layers_dimensions[i],layers_dimensions[i+1],activations[i]))
  def forward_pass(self, input):
    hidden_state=input
    for i in range (len(self.layers)):
      hidden_state=self.layers[i].forward(hidden_state)
    return hidden_state 
## You can more methods, including train (for updating parameters), evaluation, accouracy, and ... ## 

# Now it's time for testing

In [ ]:
# Testing activations
print(sigmoid(-1),tanh(-1),relu(-1))

0.2689414213699951 -0.7615941559557649 0


In [ ]:
# Testing layer class
test_layer=layer(10,30,'i')
input1=np.random.randn(10)
test_layer.forward(input1)

The activation argument is not valid for this layer. Tanh is selected as default


array([-0.93353496, -0.97908677,  0.98920752,  0.97304912, -0.91979969,
       -0.38530038,  0.99330304, -0.62128213, -0.53066471,  0.83361013,
       -0.68022727,  0.86479381,  0.65063539,  0.97093362,  0.99679228,
       -0.99971306,  0.99999407,  0.99096745, -0.97457004,  0.19962093,
       -0.92545288,  0.97153473, -0.58388052,  0.98457424, -0.46088299,
        0.99874799, -0.51049045, -0.99875616, -0.94919186,  0.05139802])

In [ ]:
print(test_layer.w[29],'\n',test_layer.b[29])

[0.41700290858265116, 1.324867262330723, -0.33567763430969566, -0.597422988102234, 0.5570689335103333, 0.6871954896968677, -1.351084209499533, -0.4422148442463709, 2.0836118016448246, -0.4992036614728939] 
 1.778665802338415


In [ ]:
test_layer.b[29]=100
test_layer.forward(input1)

array([-0.93353496, -0.97908677,  0.98920752,  0.97304912, -0.91979969,
       -0.38530038,  0.99330304, -0.62128213, -0.53066471,  0.83361013,
       -0.68022727,  0.86479381,  0.65063539,  0.97093362,  0.99679228,
       -0.99971306,  0.99999407,  0.99096745, -0.97457004,  0.19962093,
       -0.92545288,  0.97153473, -0.58388052,  0.98457424, -0.46088299,
        0.99874799, -0.51049045, -0.99875616, -0.94919186,  1.        ])

In [ ]:
# Testing neural network class
test_net=NN([5,10,15,20],['s','sigmoid','e'])

The activation argument is not valid for this layer. Tanh is selected as default
The activation argument is not valid for this layer. Tanh is selected as default


In [ ]:
len(test_net.layers)

3

In [ ]:
test_net.layers[1].w[1]

[-0.7397661284243673,
 0.503316016356973,
 -1.0431681004349482,
 0.5441639352955582,
 0.2682470771743236,
 0.3787298766210846,
 -0.707159964349045,
 1.2036701117326185,
 -0.5936589649792265,
 0.6074951794970046]

In [ ]:
input2=np.random.randn(5)
input2
test_net.forward_pass(input2)

array([-0.9999611 ,  0.99156094,  0.90188928,  0.73662001, -0.70641376,
        0.99984406, -0.9798219 , -0.96223775,  0.93403123,  0.36627584,
        0.99611893,  0.96871388,  0.94179617,  0.91431363, -0.547283  ,
        0.97880884, -0.89746293,  0.99449513, -0.2264744 , -0.5639643 ])

In [ ]:
test_net.layers[2].b[19]=100
test_net.layers[2].b[19]

100

In [ ]:
test_net.forward_pass(input2)

array([-0.9999611 ,  0.99156094,  0.90188928,  0.73662001, -0.70641376,
        0.99984406, -0.9798219 , -0.96223775,  0.93403123,  0.36627584,
        0.99611893,  0.96871388,  0.94179617,  0.91431363, -0.547283  ,
        0.97880884, -0.89746293,  0.99449513, -0.2264744 ,  1.        ])

In [ ]:
test_net.layers[2].w[18][14]=-1000
test_net.layers[2].w[18][14]

-1000

In [ ]:
test_net.forward_pass(input2)

array([-0.9999611 ,  0.99156094,  0.90188928,  0.73662001, -0.70641376,
        0.99984406, -0.9798219 , -0.96223775,  0.93403123,  0.36627584,
        0.99611893,  0.96871388,  0.94179617,  0.91431363, -0.547283  ,
        0.97880884, -0.89746293,  0.99449513, -1.        ,  1.        ])

In [ ]:
test_net.layers[0].w[9][4]=-1000
test_net.layers[0].w[9][4]

-1000

In [ ]:
test_net.forward_pass(input2)

array([-0.99996564,  0.98691248,  0.98304989,  0.92102293, -0.96387704,
        0.9995454 , -0.98587014, -0.98809055,  0.73913584,  0.52810047,
        0.94186828,  0.93412322,  0.86911019,  0.97699998, -0.64881778,
        0.98313544, -0.88168777,  0.9897068 , -1.        ,  1.        ])

In [ ]:
test_layers=np.random.randint(10, high=100, size=201)
print(test_layers)
test_activations= ['tanh' for i in range(200)]
test_deep_net=NN(test_layers,test_activations)
print('\n',len(test_deep_net.layers),'\n')
test_deep_net.forward_pass(np.random.randn(test_layers[0]))

[93 74 80 81 33 39 18 31 50 11 44 30 72 26 60 83 95 14 54 49 73 80 86 80
 19 53 84 40 68 36 74 27 80 74 62 27 37 81 98 19 48 20 81 78 40 61 61 57
 18 39 78 49 14 97 53 61 38 39 69 32 24 28 65 73 80 30 63 97 89 67 44 24
 14 50 40 76 12 65 33 74 41 96 60 87 84 61 65 82 69 93 51 55 14 65 90 35
 60 28 34 77 56 66 40 70 30 27 68 15 95 21 69 22 67 54 45 81 72 89 32 98
 16 47 45 58 46 93 81 16 61 61 48 77 16 54 62 97 24 27 34 27 17 29 72 75
 46 45 97 31 96 41 89 35 46 13 22 97 80 92 71 32 35 33 77 80 12 69 19 27
 86 51 99 73 55 63 90 93 44 89 63 99 19 16 38 64 53 99 99 85 36 50 28 33
 95 68 50 14 47 24 85 63 65]

 200 



array([-0.99999969, -0.99979304,  0.99746106, -0.9999746 ,  1.        ,
       -0.99950025, -0.37219563,  0.83246854, -0.718536  ,  0.99999998,
       -0.99628073, -0.99792352,  0.99999996,  0.99864125,  0.98584824,
       -1.        ,  0.96877322,  0.99994823, -0.99500467,  1.        ,
       -1.        ,  1.        ,  0.96604815,  0.99999999,  1.        ,
       -0.96926666,  0.99864708, -0.84627744,  0.33692842,  0.98086042,
       -0.27669548, -0.99249554, -0.9380365 , -0.96584823,  1.        ,
        0.99773698,  1.        ,  0.978568  ,  1.        , -0.99999734,
       -0.52171139,  0.99972689, -0.99999139,  1.        ,  0.93282569,
        0.99999192,  0.60247861, -0.99657484, -0.999986  , -0.89935116,
       -1.        , -0.99941792, -0.6565373 ,  0.99985522,  1.        ,
       -1.        , -0.80575161, -1.        , -1.        , -0.99982908,
        0.95818706, -0.99995566, -0.78056864,  0.93569328, -0.99999266])

In [ ]:
test_layers=np.random.randint(10, high=100, size=51)
print(test_layers)
test_activations= ['tanh' for i in range(50)]
test_deep_net=NN(test_layers,test_activations)
print('\n',len(test_deep_net.layers),'\n')
test_deep_net.forward_pass(np.random.randn(test_layers[0]))

[96 65 86 58 83 98 92 62 46 49 63 96 53 50 33 68 66 33 27 49 79 87 66 31
 22 91 69 45 43 13 44 43 59 57 69 34 90 80 50 60 19 25 31 10 34 53 83 13
 23 19 26]

 50 



array([ 0.92612539, -0.9635595 , -0.8949445 ,  0.80202444,  0.10086739,
        0.98993932, -0.73592763, -0.99349351, -0.99733665, -0.99998317,
       -0.98846613, -0.99999839,  0.60141797, -0.96490394, -0.36459333,
       -0.84622335, -0.7661992 ,  0.97128684,  0.9939122 , -0.93520048,
       -0.9918251 ,  0.99950576,  0.8530045 , -0.99999576, -0.99498954,
        0.60336811])